
language: python
sudo: false
virtualenv:
  system_site_packages: true
addons:
   apt:
      packages:
      - gfortran
      - nose
      - libgfortran
      - coverage

matrix:
  include:
    # "Recommended" environments: More recent versions, for Py2 and Py3.
    - python: "3.5"
      env: DEPS="" DISTRIB="conda" COVERAGE="true"

# installation
install:
  - source install.sh
# command to run tests
script:
  - travis_wait 20 'test_script.sh'
after_success:
  - coveralls
