
language: python
sudo: true
python:
  - "3.5"
#virtualenv:
#  system_site_packages: true
#addons:
#   apt:
#      packages:
#      - gfortran
#      - nose
#      - libgfortran
#      - coverage

#matrix:
#  include:
#    # "Recommended" environments: More recent versions, for Py2 and Py3.
#    - python: "3.5"
#      env: DEPS="" DISTRIB="conda" COVERAGE="true"
#
## installation
install:
#  - pip install -r requirements.txt
#  - python3 setup.py install
   - source install.sh
   - python3 -m textblob.download_corpora
## command to run tests
script:
#   - nosetests
  - python3 -m "nose" --with-coverage --cover-package=chatbotQuery
#  - travis_wait 20 'test_script.sh'
#after_success:
#  - coveralls
